# Generated by Django 3.2.16 on 2023-01-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230128_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='advert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='api.advert'),
        ),
    ]
