# Generated by Django 3.2.16 on 2023-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chat_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
