# Generated by Django 3.2.16 on 2023-01-29 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230129_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
